
# Server settings
#server:
#    port:8080
#    address:localhost

# DATASOURCE
#jdbc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: admin358

# SPRING PROFILES
#spring:
    # HTTP ENCODING
#    http:
#        encoding.charset: UTF-8
#        encoding.enable: true
#        encoding.force: true
    # thymeleaf
#    thymeleaf:
#      cache: false
#      check-template: true
#      check-template-location: true
#      content-type: text/html
#      enabled: true
#      encoding: utf-8
#      mode: HTML5
#      prefix: classpath:/templates/
#      suffix: .html

# WeiXin Configuration
#weixin:
#    mp:
#       appid: xx
#       secret: ee
#       token: weixin
#       aeskey:

# MyBatis
#mybatis:
#    typeAliasesPackage: top.haw358.springboot.model
#    mapperLocations: classpath:/mapper/*.xml
#    configLocation: classpath:/mybatis-config.xml

#mapper
#mappers 多个接口时逗号隔开
#mapper:
#  mappers:
#    - BaseMapper
#  not-empty: false
#  identity: MYSQL

#pagehelper
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

# LOGGING
#logging:
#    level:
#        root: warn
